namespace NuvTools.Blockchain;

/// <summary>
/// Represents a typed entry retrieved from a ledger (e.g., Azure Confidential Ledger).
/// </summary>
/// <typeparam name="T">The type of the entry content.</typeparam>
public class LedgerEntry<T> : LedgerEntryBase<T>
{
    /// <summary>
    /// The unique transaction ID generated by the ledger.
    /// </summary>
    public required string TransactionId { get; init; }

    /// <summary>
    /// Optional logical collection id (or sub ledger Id).
    /// </summary>
    public string? CollectionId { get; init; }
}

/// <summary>
/// Base class for ledger entries containing the core content and timestamp.
/// </summary>
/// <typeparam name="T">The type of the entry content.</typeparam>
public class LedgerEntryBase<T>
{
    /// <summary>
    /// The business record originally stored in the ledger.
    /// </summary>
    public required T Content { get; init; }

    /// <summary>
    /// The UTC timestamp when the entry was committed and sealed by the ledger.
    /// </summary>
    public required DateTime CommitTimeUtc { get; init; }
}
